name: Run MATLAB Build on Self-Hosted Runner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2021a
          
      - name: Run MATLAB Command
        uses: matlab-actions/run-command@v1.1.2
        with:
          command: buildResults = compiler.build.productionServerArchive('addmatrix.m','Verbose','on');
        env:
          MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}
          MATHWORKS_ACCOUNT: ${{ secrets.MATHWORKS_ACCOUNT }}
